In [3]:
import gym

In [4]:
e = gym.make('CartPole-v0')
e


<TimeLimit<OrderEnforcing<PassiveEnvChecker<CartPoleEnv<CartPole-v0>>>>>

In [10]:
obs = e.reset() # it is random 
obs
# Here, we reset the environment and obtained the first observation (we always need to reset
# the newly created environment). As I said, the observation is four numbers, so let's check how
# we can know this in advance

(array([ 0.04985859,  0.0495961 ,  0.03638246, -0.00027351], dtype=float32),
 {})

In [12]:
e.action_space

Discrete(2)

In [13]:
e.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

The action_space field is of the Discrete type, so our actions will be just 0 or 1, where 0
means pushing the platform to the left and 1 means to the right. The observation space is of
Box(4,) , which means a vector of size 4 with values inside the [−inf, inf] interval

In [14]:
e.step(0)

c:\Users\mehrd\anaconda3\envs\torch\lib\site-packages\gym\utils\passive_env_checker.py:233: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(terminated, (bool, np.bool8)):


(array([ 0.05085051, -0.14602824,  0.03637699,  0.30366287], dtype=float32),
 1.0,
 False,
 False,
 {})

Here, we pushed our platform to the left by executing the action 0 and got the tuple of four
elements: 
 
* A new observation, which is a new vector of four numbers  
* A reward of 1.0   
* The done flag with value False , which means that the episode is not over yet and we are more or less okay  
* Extra information about the environment, which is an empty dictionary

In [15]:
e.action_space.sample()

0

In [17]:
e.action_space.sample()

1

In [22]:
print(e.action_space.sample())
print(e.action_space.sample())
print(e.action_space.sample())
print(e.action_space.sample())
print(e.action_space.sample())
print(e.action_space.sample())
print(e.action_space.sample())


1
1
0
1
1
1
0


In [24]:
print(e.observation_space.sample())
print(e.observation_space.sample())
print(e.observation_space.sample())
print(e.observation_space.sample())
print(e.observation_space.sample())
print(e.observation_space.sample())

[-4.3074541e+00  3.1582259e+38 -2.2640420e-01 -2.1411217e+38]
[-1.9448510e+00  1.7938538e+38  2.3863353e-01  3.3870768e+38]
[1.9237388e+00 2.9939379e+37 2.1958783e-01 3.0823241e+38]
[-2.1351635e+00  2.8346408e+38  3.5855076e-01  1.1654986e+37]
[-5.4128319e-02  6.7715912e+37 -2.4070342e-01 -5.5553135e+37]
[6.5979570e-01 1.1226958e+38 1.5964280e-01 1.2782051e+38]


This method returned a random sample from the underlying space, which in the case of our
Discrete action space means a random number of 0 or 1, and for the observation space
means a random vector of four numbers. The random sample of the observation space may
not look useful, and this is true, but the sample from the action space could be used when we
are not sure how to perform an action. This feature is especially handy because you don't
know any RL methods yet, but we still want to play around with the Gym environment. Now
that you know enough to implement your first randomly behaving agent for CartPole, let's do
it

In [45]:
import gym
if __name__ == "__main__":
    env = gym.make("CartPole-v0")
    total_reward = 0.0
    total_steps = 0
    obs = env.reset()
# Here, we created the environment and initialized the counter of steps and the reward accumulator. 
# On the last line, we reset the environment to obtain the first observation (which we will
# not use, as our agent is stochastic)
    while True:
        action = env.action_space.sample()
        obs, reward , done, _, _ = env.step(action)
        total_reward += reward
        total_steps += 1

        if done:
            break
    print(f"Episode is done in {total_steps} steps, and total reward was {total_reward}")




Episode is done in 29 steps, and total reward was 29.0


In [33]:
env.step(action)

c:\Users\mehrd\anaconda3\envs\torch\lib\site-packages\gym\envs\classic_control\cartpole.py:177: UserWarning: WARN: You are calling 'step()' even though this environment has already returned terminated = True. You should always call 'reset()' once you receive 'terminated = True' -- any further steps are undefined behavior.
  logger.warn(


(array([-0.13661607,  0.36407408,  0.22710562,  0.12744747], dtype=float32),
 0.0,
 True,
 False,
 {})